### ISSUE TITLE
Add documentation about how to edit config.ini.php? 

### ISSUE THREAD

**Issue by mlissner** [crazy-max/docker-matomo#60]
#### Steps to reproduce this issue

1. Read readme
2. Note that it says to edit config.ini.php
3. `locate config.ini.php`
4. `tree -R / | grep config.ini.php`

#### Expected behaviour

The docs should say how to find and edit the file. 

#### Actual behaviour

It's really hard to find the file. I eventually found it by doing `docker volume inspect`, which then showed its location. Maybe there's a better/easier way?

I'll be happy to tweak the docs if a maintainer agrees it's a good idea.

**Comment by crazy-max** [comment]
@mlissner As stipulated in the README ([Volumes section](https://github.com/crazy-max/docker-matomo#volumes)), `/data` contains configuration. In your case `/data/config`.

**Comment by mlissner** [comment]
Yes, but maybe it's because I don't use docker all the time, but I have no idea how to go from `/data` to a file I can edit: 

 - `/data` isn't a directory on the host....
 - `/data` might be in the container?
 - But the container doesn't have an editor installed...
 - And it's alpine linux, so I don't know how to install it...

You can see how this is going. Maybe there's a key trick I'm missing. The way I did it was to do a `docker volume inspect`, which showed me where the volume was on the host's disk, and I could edit from there.

**Comment by crazy-max** [comment]
@mlissner 

> I don't use docker all the time

If your issue is directly related to Matomo and not this Docker image I suggest you open an issue on the [official repository](https://github.com/matomo-org/matomo).

> 
>  * `/data` isn't a directory on the host....
>  * `/data` might be in the container?
>  * But the container doesn't have an editor installed...
>  * And it's alpine linux, so I don't know how to install it...
> 
> 
> You can see how this is going. Maybe there's a key trick I'm missing. The way I did it was to do a `docker volume inspect`, which showed me where the volume was on the host's disk, and I could edit from there.

Ok so what I see is that it's more an issue of misunderstanding the concepts around Docker and volumes than a problem with this image itself. Here are some resources that might help you:

* https://docs.docker.com/storage/volumes/
* https://docs.docker.com/storage/
* https://flaviocopes.com/docker-access-files-outside-container/
