### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by lselect** [crazy-max/docker-matomo#77]
### Behaviour

![image](https://user-images.githubusercontent.com/13584174/119112504-b9144800-ba56-11eb-95ec-5f3719437dbe.png)

#### Steps to reproduce this issue

1.
2.
3.

#### Expected behaviour

> Tell me what should happen

#### Actual behaviour

> Tell me what happens instead

### Configuration

* Docker version (type `docker --version`) :  Docker version 20.10.6, build 370c289
* Docker compose version if applicable (type `docker-compose --version`) :  docker-compose version 1.29.2, build unknown
* Platform (Debian 9, Ubuntu 18.04, ...) : centos7
* System info (type `uname -a`) :  Linux localhost.localdomain 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

### Docker info

```
> Output of command `docker info`
```
![image](https://user-images.githubusercontent.com/13584174/119112790-0c869600-ba57-11eb-8771-16ad0a9e8d07.png)

### Logs

```
> Container logs (set LOG_LEVEL to debug if applicable)
```

**Comment by crazy-max** [comment]
@lselect Would need:

* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...
* Logs

**Comment by lselect** [comment]
![image](https://user-images.githubusercontent.com/13584174/119283532-f69fed80-bc6f-11eb-9b58-431e42df929f.png)
 All your example config files, I never changed them.
Can not use it like this?

**Comment by crazy-max** [comment]
@lselect Your issue is that you have not changed some settings in the `docker-compose.yml` and env files like [this one](https://github.com/crazy-max/docker-matomo/blob/a919136466c7d05e5b63272e3c016ff410562a72/examples/traefik/docker-compose.yml#L86).

I have updated the [basic example](https://github.com/crazy-max/docker-matomo/tree/master/examples/compose) to remove traefik service. This way it should work with `http://localhost:8000`.

**Comment by crazy-max** [comment]
If you still want to use Traefik I suggest to read their documentation about routers, services and configuration discovery: https://docs.traefik.io/
